### ISSUE TITLE
Add strong name

### ISSUE THREAD

**Issue by xPaw** [ksgfk/TinyEXR.NET#3]
Can you please add a .snk and sign the assembly? I want to add it to my libraray, but all the dependencies also require it.

https://learn.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name

**Comment by ksgfk** [comment]
I have signed strong name for the Nuget package. You can find signed assembly in version `v0.3.8` in nuget

By the way, I found the following instructions in the document. [url](https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named#why-strong-name-your-assemblies)
> For .NET Core and .NET 5+, strong-named assemblies do not provide material benefits. The runtime never validates the strong-name signature, nor does it use the strong-name for assembly binding.

It looks like that strong name is not work in .NET5+. Do we really need it?

**Comment by xPaw** [comment]
There's still some cases like InternalsVisibleToAttribute with a public key, and providing an identity to the dll in general.
